"""High-level gizmo contracts and official UI catalog helpers.

Creator tools may use ``GizmoHandle``/``GizmoManipulator`` for optimized
viewport handles, but the supported vocabulary of styles, actors, previews and
overlays is documented by :mod:`laserprog_studio.tool_api.ui_catalog`.
"""
from __future__ import annotations

from laserprog_studio.tool_core.gizmos import GizmoHandle, GizmoManipulator, GizmoManager

from .ui_motifs import (
    CreatorUiMotifBuilder,
    CreatorUiMotifSnapshot,
    OFFICIAL_CREATOR_UI_MOTIF_FAMILIES,
    apply_creator_ui_motif_visibility,
    apply_gizmo_ui_motif_visibility,
    build_creator_ui_motifs,
    build_gizmo_ui_motifs,
    clear_creator_ui_motifs,
    clear_gizmo_ui_motifs,
    iter_creator_ui_motif_families,
    iter_gizmo_ui_motif_families,
    refresh_creator_ui_camera,
    refresh_creator_ui_interaction,
    refresh_creator_ui_drag,
    refresh_creator_ui_motifs,
    refresh_gizmo_ui_camera,
    refresh_gizmo_ui_interaction,
    refresh_gizmo_ui_drag,
    refresh_gizmo_ui_motifs,
    set_creator_ui_motif_family_visible,
)

from .ui_catalog import (
    GIZMO_UI_FAMILIES,
    TOOL_GIZMO_RECOMMENDATIONS,
    CreatorUiDirectionLayer,
    CreatorUiFamily,
    CreatorUiFamilyId,
    CreatorUiItem,
    GizmoCatalogItem,
    GizmoUiFamily,
    ToolGizmoRecommendation,
    ToolUiRecommendation,
    all_recommended_line_styles,
    all_recommended_point_styles,
    creator_ui_catalog_markdown,
    creator_ui_direction_layers,
    creator_ui_direction_markdown,
    get_creator_ui_family,
    get_gizmo_ui_family,
    gizmo_ui_catalog_markdown,
    iter_creator_ui_families,
    iter_gizmo_ui_families,
    iter_tool_ui_recommendations,
    list_creator_ui_families,
    overlay_kind_choices,
    recommendations_for_tool,
)

__all__ = [
    "GIZMO_UI_FAMILIES",
    "TOOL_GIZMO_RECOMMENDATIONS",
    "CreatorUiDirectionLayer",
    "CreatorUiFamily",
    "CreatorUiFamilyId",
    "CreatorUiItem",
    "CreatorUiMotifBuilder",
    "CreatorUiMotifSnapshot",
    "OFFICIAL_CREATOR_UI_MOTIF_FAMILIES",
    "apply_creator_ui_motif_visibility",
    "apply_gizmo_ui_motif_visibility",
    "build_creator_ui_motifs",
    "build_gizmo_ui_motifs",
    "clear_creator_ui_motifs",
    "clear_gizmo_ui_motifs",
    "iter_creator_ui_motif_families",
    "iter_gizmo_ui_motif_families",
    "refresh_creator_ui_camera",
    "refresh_creator_ui_interaction",
    "refresh_creator_ui_drag",
    "refresh_creator_ui_motifs",
    "refresh_gizmo_ui_camera",
    "refresh_gizmo_ui_interaction",
    "refresh_gizmo_ui_drag",
    "refresh_gizmo_ui_motifs",
    "set_creator_ui_motif_family_visible",
    "GizmoCatalogItem",
    "GizmoHandle",
    "GizmoManipulator",
    "GizmoManager",
    "GizmoUiFamily",
    "ToolGizmoRecommendation",
    "ToolUiRecommendation",
    "all_recommended_line_styles",
    "all_recommended_point_styles",
    "creator_ui_catalog_markdown",
    "creator_ui_direction_layers",
    "creator_ui_direction_markdown",
    "get_creator_ui_family",
    "get_gizmo_ui_family",
    "gizmo_ui_catalog_markdown",
    "iter_creator_ui_families",
    "iter_gizmo_ui_families",
    "iter_tool_ui_recommendations",
    "list_creator_ui_families",
    "overlay_kind_choices",
    "recommendations_for_tool",
]
