# -*- coding: utf-8 -*-
"""Shared paths and expected files for static architecture guards."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STUDIO = ROOT / "src" / "laserprog_studio"
WINDOW = STUDIO / "window.py"

EXPECTED_WINDOW_METHODS = {"__init__", "eventFilter", "keyPressEvent", "keyReleaseEvent", "closeEvent", "set_transform_mode", "update_gizmo", "request_render", "render_now", "flush_render"}
MIN_EXTRACTED_METHODS = 300
REQUIRED_MODULES = [
    STUDIO / "ui" / "panels.py",
    STUDIO / "ui" / "configurable_toolbar.py",
    STUDIO / "ui" / "tool_panel_catalog.py",
    STUDIO / "ui" / "tool_panel_factory.py",
    STUDIO / "ui" / "tool_panel_widgets.py",
    STUDIO / "application" / "toolbar_controller.py",
    STUDIO / "application" / "layout_controller.py",
    STUDIO / "application" / "export_controller.py",
    STUDIO / "application" / "render_output_controller.py",
    STUDIO / "application" / "preview_controller.py",
    STUDIO / "application" / "tool_preview_controller.py",
    STUDIO / "application" / "tool_lifecycle_controller.py",
    STUDIO / "application" / "tool_help_controller.py",
    STUDIO / "tooling" / "help_docs.py",
    STUDIO / "application" / "boolean_controller.py",
    STUDIO / "application" / "fabrication_preview_controller.py",
    STUDIO / "application" / "modifier_preview_controller.py",
    STUDIO / "application" / "texture_projection_controller.py",
    STUDIO / "application" / "texture_gizmo_controller.py",
    STUDIO / "application" / "texture_gizmo_target_service.py",
    STUDIO / "application" / "texture_gizmo_live_update_service.py",
    STUDIO / "application" / "texture_gizmo_event_service.py",
    STUDIO / "application" / "texture_gizmo_render_service.py",
    STUDIO / "application" / "texture_gizmo_drag_service.py",
    STUDIO / "application" / "texture_gizmo_math.py",
    STUDIO / "application" / "texture_gizmo_qt.py",
    STUDIO / "controllers" / "__init__.py",
    STUDIO / "controllers" / "interaction.py",
    STUDIO / "controllers" / "interaction_gizmo_refresh.py",
    STUDIO / "controllers" / "interaction_picking.py",
    STUDIO / "controllers" / "interaction_value_fields.py",
    STUDIO / "controllers" / "selection_box.py",
    STUDIO / "controllers" / "scene.py",
    STUDIO / "controllers" / "preview_controller.py",
    STUDIO / "controllers" / "state_bridge.py",
    STUDIO / "controllers" / "tool_selection_policy.py",
    STUDIO / "controllers" / "layout_restore.py",
    STUDIO / "controllers" / "tool_lifecycle.py",
    STUDIO / "controllers" / "split_plane_tool.py",
    STUDIO / "controllers" / "boolean_actions.py",
    STUDIO / "controllers" / "clipboard_actions.py",
    STUDIO / "controllers" / "scene_edit_actions.py",
    STUDIO / "controllers" / "history_actions.py",
    STUDIO / "controllers" / "booleans_clipboard_history.py",
    STUDIO / "controllers" / "exporting.py",
    STUDIO / "controllers" / "render_output.py",
    STUDIO / "runtime_state.py",
    STUDIO / "app_context.py",
    STUDIO / "services" / "geometry.py",
    STUDIO / "geometry_ops" / "__init__.py",
    STUDIO / "geometry_ops" / "result.py",
    STUDIO / "tooling" / "base.py",
    STUDIO / "tooling" / "registry.py",
    STUDIO / "tooling" / "ids.py",
    STUDIO / "modifiers" / "base.py",
    STUDIO / "modifiers" / "registry.py",
    STUDIO / "parameters" / "base.py",
    STUDIO / "parameters" / "panel_factory.py",
    STUDIO / "state" / "selection_state.py",
    STUDIO / "state" / "preview_state.py",
    STUDIO / "state" / "ui_layout_state.py",
    STUDIO / "state" / "texture_gizmo_state.py",
    STUDIO / "state" / "planar_tool_state.py",
    STUDIO / "application" / "planar_tool_controller.py",
    STUDIO / "application" / "planar_preview_service.py",
    STUDIO / "application" / "planar_report_service.py",
    STUDIO / "tooling" / "vent_generator" / "panel.py",
    STUDIO / "tooling" / "vent_generator" / "settings.py",
    STUDIO / "planar_tools" / "__init__.py",
    STUDIO / "planar_tools" / "contracts.py",
    STUDIO / "planar_tools" / "orientation.py",
    STUDIO / "planar_tools" / "draft_model.py",
    STUDIO / "planar_tools" / "vent_model.py",
    STUDIO / "planar_tools" / "vent_constraints.py",
    STUDIO / "planar_tools" / "vent_flare.py",
    STUDIO / "planar_tools" / "path_sampling.py",
    STUDIO / "planar_tools" / "pointer.py",
    STUDIO / "planar_tools" / "mesh_generation.py",
    STUDIO / "planar_tools" / "validation.py",
    STUDIO / "tooling" / "planar_tool_blueprints.py",
    STUDIO / "rendering" / "display_modes.py",
    STUDIO / "rendering" / "handles.py",
    STUDIO / "rendering" / "scene_renderer.py",
    STUDIO / "rendering" / "materials.py",
    STUDIO / "domain" / "material.py",
    STUDIO / "domain" / "texture_asset.py",
    STUDIO / "primitives" / "base.py",
    STUDIO / "primitives" / "registry.py",
    STUDIO / "primitives" / "generators.py",
    STUDIO / "tooling" / "primitive_tool.py",
    STUDIO / "tooling" / "extension_api.py",
    STUDIO / "engraving" / "layers.py",
    STUDIO / "engraving" / "pipeline.py",
    STUDIO / "assets" / "texture_assets.py",
    STUDIO / "io" / "three_mf" / "contracts.py",
]
