# -*- coding: utf-8 -*-
from __future__ import annotations

from .ids import TOOL_TEXTURE_PROJECTION

HANDLE_MOVE = f"{TOOL_TEXTURE_PROJECTION}:move"
HANDLE_ROTATE = f"{TOOL_TEXTURE_PROJECTION}:rotate"
HANDLE_SCALE = f"{TOOL_TEXTURE_PROJECTION}:scale"
HANDLE_STRETCH_U_NEG = f"{TOOL_TEXTURE_PROJECTION}:stretch_u_neg"
HANDLE_STRETCH_U_POS = f"{TOOL_TEXTURE_PROJECTION}:stretch_u_pos"
HANDLE_STRETCH_V_NEG = f"{TOOL_TEXTURE_PROJECTION}:stretch_v_neg"
HANDLE_STRETCH_V_POS = f"{TOOL_TEXTURE_PROJECTION}:stretch_v_pos"
OVERLAY_ID = f"{TOOL_TEXTURE_PROJECTION}.projector_overlay"

__all__ = ["HANDLE_MOVE", "HANDLE_ROTATE", "HANDLE_SCALE", "HANDLE_STRETCH_U_NEG", "HANDLE_STRETCH_U_POS", "HANDLE_STRETCH_V_NEG", "HANDLE_STRETCH_V_POS", "OVERLAY_ID"]
