# -*- coding: utf-8 -*-
from __future__ import annotations

TOOL_NONE = "none"
TOOL_BOX = "box"
TOOL_LAYFLAT = "layflat"
TOOL_JOINT = "joint"
TOOL_PRIMITIVE = "primitive"
TOOL_ENGRAVING = "engraving"
TOOL_MATERIAL = "material"
TOOL_TEXTURE_PROJECTION = "texture_projection"
TOOL_PLAN_TRACE = "plan_trace"
TOOL_VENT_GENERATOR = "vent_generator"
TOOL_MECHANICAL_MOTION = "mechanical_motion"
TOOL_FOLDING = "folding"
TOOL_CLOTH = "cloth"
TOOL_VOLUME_MEASURE = "volume_measure"
TOOL_ACOUSTIC_DIFFUSER = "acoustic_diffuser"
TOOL_CORE_DIAGNOSTIC = "tool_core_diagnostic"
TOOL_SMART_SURFACE_SELECTION_TEST = "smart_surface_selection_test"
TOOL_GIZMO_CATALOG = "gizmo_catalog"
TOOL_MOD_SPLIT = "modifier_split"
TOOL_MOD_SIMPLIFY = "modifier_simplify"
TOOL_MOD_RELIEF = "modifier_relief"
TOOL_MOD_EXTRUDE_DOWN = "modifier_extrude_down"
TOOL_MOD_HOLLOW = "modifier_hollow"
TOOL_MOD_REPAIR = "modifier_repair"

TRANSFORM_NONE = "none"
TRANSFORM_TRANSLATE = "translate"
TRANSFORM_ROTATE = "rotate"
TRANSFORM_SCALE = "scale"
