# -*- coding: utf-8 -*-
"""Tool: procedural joint builder (prototype).

V1: works on 2 selected boards (A then B).
- Detects a contact (distance <= tolerance) in 2D (coplanar boards).
- Adds a rectangular tab on A.
- Carves a matching slot on B (with clearance).

Known limitations (v1):
- Single joint, centered on the closest contact area.

V2:
- Supports non-coplanar boards by estimating a joint axis from normals/centroids.
"""

from __future__ import annotations

import json
import math
import time
import tkinter as tk
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from tkinter import messagebox, ttk
from typing import Callable

import numpy as np
from shapely.geometry import LineString, MultiPoint, Point, Polygon, box as shapely_box
from shapely.ops import nearest_points, unary_union, triangulate

from laserprog_studio.domain.work_model import WorkMesh

TOOL_ID = "joint_builder"
TOOL_NAME = "Joint builder (prototype)"
DEBUG_LOG_VERSION = 22

DEFAULT_SETTINGS = {
    "touch_tolerance_mm": 0.05,
    "clearance_mm": 0.15,
    "joint_size_mm": 10.0,
    "joint_count": 1,
    "joint_edge_margin_mm": 2.0,
    "single_depth_probe": True,
    "debug_log": False,
    "method": "tab_slot_simple",  # future: finger, dovetail, etc.
}

METHOD_LABELS = {
    "tab_slot_simple": "Simple tab/slot (1 tab)",
}

class AutoSaveSettings:
    def __init__(self, path: Path, defaults: dict) -> None:
        self.path = path
        self.defaults = defaults.copy()
        self.data = self.defaults.copy()
        self.load()

    def load(self) -> None:
        if self.path.exists():
            try:
                loaded = json.loads(self.path.read_text(encoding="utf-8"))
                if isinstance(loaded, dict):
                    self.data.update(loaded)
            except Exception:
                pass
        else:
            self.save()

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(self.data, indent=2, ensure_ascii=False), encoding="utf-8")

@dataclass(frozen=True)
class PlankBasis:
    origin: np.ndarray  # (3,)
    u: np.ndarray  # (3,)
    v: np.ndarray  # (3,)
    n: np.ndarray  # (3,)
    w_min: float
    w_max: float

    @property
    def thickness(self) -> float:
        return float(self.w_max - self.w_min)

    def project_2d(self, p: tuple[float, float, float]) -> tuple[float, float]:
        x = np.dot(np.array(p) - self.origin, self.u)
        y = np.dot(np.array(p) - self.origin, self.v)
        return (float(x), float(y))

    def lift_3d(self, x: float, y: float, w: float) -> tuple[float, float, float]:
        p = self.origin + self.u * x + self.v * y + self.n * w
        return (float(p[0]), float(p[1]), float(p[2]))

def _normalize(v: np.ndarray) -> np.ndarray:
    n = float(np.linalg.norm(v))
    if n <= 1e-12:
        return v
    return v / n

def compute_basis(mesh: WorkMesh) -> PlankBasis:
    verts = np.array(mesh.vertices, dtype=float)
    if len(verts) < 8:
        raise ValueError("Mesh too small to estimate a board basis.")
    origin = verts.mean(axis=0)
    centered = verts - origin
    cov = centered.T @ centered / max(1, len(verts))
    w, vecs = np.linalg.eigh(cov)  # ascending
    n = _normalize(vecs[:, 0])
    v = _normalize(vecs[:, 1])
    u = _normalize(vecs[:, 2])
    # Ensure right-handed basis
    if np.dot(np.cross(u, v), n) < 0:
        v = -v
    ws = centered @ n
    w_min = float(ws.min())
    w_max = float(ws.max())
    return PlankBasis(origin=origin, u=u, v=v, n=n, w_min=w_min, w_max=w_max)

def _effective_joint_thickness(raw_thickness: float, face_width_hint: float) -> float:
    """Useful thickness for sizing joint volumes.

    After one or more boolean operations, `compute_basis(...).thickness` can be polluted
    by already-added pins or already-subtracted holes. In this case, the PCA thickness
    can become close to 2x the real board thickness, doubling the length of the
    new pin.

    The joint face provides a more reliable measure for boxes generated by the tool:
    its small dimension matches the nominal board thickness at the contact area.
    Use this value as a safety guard whenever the global thickness looks suspicious.
    """
    raw = float(raw_thickness)
    hint = float(face_width_hint)
    if hint > 1e-6:
        if not (raw > 1e-6):
            return hint
        # If the global measure is clearly larger than the contact width,
        # it is probably contaminated by a previous pin.
        if raw > hint * 1.30:
            return hint
        # If it is almost the same value, force the contact value to avoid
        # numeric drift such as 6.10 -> 12.20 instead of 12.00.
        if abs(raw - hint) <= max(0.25, hint * 0.12):
            return hint
    if raw > 1e-6:
        return raw
    return 3.0

def footprint_polygon(mesh: WorkMesh, basis: PlankBasis) -> Polygon:
    polys = []
    for a, b, c in mesh.triangles:
        p0 = basis.project_2d(mesh.vertices[a])
        p1 = basis.project_2d(mesh.vertices[b])
        p2 = basis.project_2d(mesh.vertices[c])
        tri = Polygon([p0, p1, p2])
        if tri.is_empty or tri.area <= 1e-6:
            continue
        polys.append(tri)
    if not polys:
        raise ValueError("Cannot compute 2D footprint (degenerate triangles).")
    geom = unary_union(polys)
    # Keep largest polygon part
    if geom.geom_type == "Polygon":
        return geom
    if geom.geom_type == "MultiPolygon":
        return max(list(geom.geoms), key=lambda g: g.area)
    raise ValueError(f"Invalid 2D footprint: {geom.geom_type}")

def oriented_rect(center: tuple[float, float], axis: tuple[float, float], length: float, width: float) -> Polygon:
    cx, cy = center
    ax, ay = axis
    norm = math.hypot(ax, ay)
    if norm <= 1e-12:
        raise ValueError("Zero axis.")
    ax /= norm
    ay /= norm
    tx, ty = -ay, ax
    hl = length / 2.0
    hw = width / 2.0
    pts = [
        (cx - ax * hl - tx * hw, cy - ay * hl - ty * hw),
        (cx + ax * hl - tx * hw, cy + ay * hl - ty * hw),
        (cx + ax * hl + tx * hw, cy + ay * hl + ty * hw),
        (cx - ax * hl + tx * hw, cy - ay * hl + ty * hw),
    ]
    return Polygon(pts)

def _triangles_for_polygon(poly: Polygon) -> list[Polygon]:
    # Prefer constrained triangulation if available (Shapely >= 2.1).
    try:
        import shapely

        cdt = getattr(shapely, "constrained_delaunay_triangles", None)
        if cdt is not None:
            gc = cdt(poly)
            return [g for g in getattr(gc, "geoms", []) if g.geom_type == "Polygon" and g.area > 1e-9]
    except Exception:
        pass

    # Fallback: triangulate (may create outside triangles) -> keep those inside.
    tris = triangulate(poly)
    kept = []
    for t in tris:
        if t.is_empty or t.area <= 1e-9:
            continue
        c = t.representative_point()
        if poly.covers(c):
            kept.append(t)
    return kept

def extrude_polygon_to_mesh(name: str, poly: Polygon, basis: PlankBasis, color: str) -> WorkMesh:
    from shapely.geometry.polygon import orient

    poly = orient(poly, sign=1.0)  # exterior CCW, holes CW
    if poly.is_empty or poly.area <= 1e-9:
        raise ValueError("Empty polygon after modification.")

    # Collect unique 2D vertices from exterior + holes.
    def ring_coords(ring) -> list[tuple[float, float]]:
        pts = list(ring.coords)
        if len(pts) >= 2 and pts[0] == pts[-1]:
            pts = pts[:-1]
        return [(float(x), float(y)) for (x, y) in pts]

    rings: list[list[tuple[float, float]]] = [ring_coords(poly.exterior)]
    for interior in poly.interiors:
        rings.append(ring_coords(interior))

    coords_unique: list[tuple[float, float]] = []
    index_of: dict[tuple[int, int], int] = {}

    def key(p: tuple[float, float]) -> tuple[int, int]:
        return (int(round(p[0] * 1_000_000)), int(round(p[1] * 1_000_000)))

    for ring in rings:
        for p in ring:
            k = key(p)
            if k not in index_of:
                index_of[k] = len(coords_unique)
                coords_unique.append(p)

    top_offset = len(coords_unique)
    vertices: list[tuple[float, float, float]] = []
    for x, y in coords_unique:
        vertices.append(basis.lift_3d(x, y, basis.w_max))
    for x, y in coords_unique:
        vertices.append(basis.lift_3d(x, y, basis.w_min))

    triangles_idx: list[tuple[int, int, int]] = []

    # Top/bottom faces
    for tri in _triangles_for_polygon(poly):
        pts = list(tri.exterior.coords)
        if len(pts) >= 2 and pts[0] == pts[-1]:
            pts = pts[:-1]
        if len(pts) != 3:
            continue
        ids = []
        for x, y in pts:
            ids.append(index_of[key((float(x), float(y)))])
        a, b, c = ids
        triangles_idx.append((a, b, c))  # top
        triangles_idx.append((top_offset + c, top_offset + b, top_offset + a))  # bottom reversed

    # Side faces for each ring
    for ring in rings:
        if len(ring) < 3:
            continue
        for i in range(len(ring)):
            p0 = ring[i]
            p1 = ring[(i + 1) % len(ring)]
            i0 = index_of[key(p0)]
            i1 = index_of[key(p1)]
            t0 = i0
            t1 = i1
            b0 = top_offset + i0
            b1 = top_offset + i1
            # Two triangles for quad
            triangles_idx.append((t0, t1, b1))
            triangles_idx.append((t0, b1, b0))

    return WorkMesh(name=name, vertices=vertices, triangles=triangles_idx, color=color)

def _as_polygon(geom) -> Polygon:
    if geom is None:
        raise ValueError("Empty geometry.")
    gt = getattr(geom, "geom_type", None)
    if gt == "Polygon":
        return geom
    if gt == "MultiPolygon":
        geoms = list(getattr(geom, "geoms", []))
        if not geoms:
            raise ValueError("Empty MultiPolygon geometry.")
        return max(geoms, key=lambda g: g.area)
    raise ValueError(f"Invalid geometry: {gt}")

def _clean_poly(geom) -> Polygon:
    poly = _as_polygon(geom)
    try:
        poly = poly.buffer(0)
    except Exception:
        pass
    return _as_polygon(poly)

def _clamp(v: float, lo: float, hi: float) -> float:
    return float(max(lo, min(hi, v)))

def _coords_in_basis(basis: PlankBasis, p3: np.ndarray) -> tuple[float, float, float]:
    d = p3 - basis.origin
    x = float(np.dot(d, basis.u))
    y = float(np.dot(d, basis.v))
    w = float(np.dot(d, basis.n))
    return x, y, w

__all__ = [name for name in globals() if not name.startswith("__")]
